---

- name: fail2ban | Ensure fail2ban.conf
  copy: src={{ item }} dest="{{ fail2ban_conf_dir }}/fail2ban.conf" backup=no owner=root group=root mode=0644
  first_available_file:
    - "fail2ban.conf.{{ ansible_os_family }}"
    - "fail2ban.conf.default"
  tags:
    - fail2ban
    - config
  notify:
    - restart fail2ban

- name: fail2ban | Set overrides for fail2ban.conf in fail2ban.local
  template: src=fail2ban.local.j2 dest="{{ fail2ban_conf_dir }}/fail2ban.local" backup=no owner=root group=root mode=0644
  tags:
    - fail2ban
    - config
  notify:
    - restart fail2ban

- name: fail2ban | Ensure jail.conf
  copy: src={{ item }} dest="{{ fail2ban_conf_dir }}/jail.conf" backup=no owner=root group=root mode=0644
  first_available_file:
    - "jail.conf.{{ ansible_os_family }}"
    - "jail.conf.default"
  tags:
    - fail2ban
    - config
  notify:
    - restart fail2ban

- debug: msg="DEBUG {{fail2ban_jails}}"

- name: fail2ban | Set overrides for jail.conf in jail.local
  template: src=jail.local.j2 dest="{{ fail2ban_conf_dir }}/jail.local" backup=no owner=root group=root mode=0644
  tags:
    - fail2ban
    - config
  notify:
    - restart fail2ban

