---
- name: assemble jail.local
  assemble:
  args:
    src:  "{{ fail2ban_dir_parts }}"
    dest: "{{ fail2ban_dir_conf }}/jail.local"
  notify:
    - restart fail2ban

- name: restart fail2ban
  service: name="{{ fail2ban_service }}" state=restarted

